name: Kairos Consulting
favicon: null
layout_spectrum: 0.24297334090806544
typography_spectrum: 0.8732894121203572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.43564317119307816
  lightness: 0.6644891111645848
  saturation: 0.06377973523922265
  rhythmicContrast: 0.39016066933982074
purpose: []
